### ISSUE TITLE
Fix "Open With" execution on path with spaces.

### ISSUE THREAD

**Issue by Scr34mik** [Solokiller/HL_Tools#106]
When model opened via "open with" menu and path has spaces, HLMV fails to read the path properly, stating that file is not found in \<partial path between spaces> : 

![image](https://user-images.githubusercontent.com/10966059/96336042-7f74fc00-1085-11eb-925c-19dcc0fc650c.png)

**Comment by Solokiller** [comment]
That's not a problem with HLMV itself, that's Windows not passing the filename with quotes. You can fix this by setting the shell open command: https://superuser.com/questions/361816/pass-command-line-arguments-to-windows-open-with

The command should be like this: `"path\to\HLMV.exe" "%1"`

Replace `path\to\HLMV.exe` with the path to where you have the program installed.

This is something that an installer can set up automatically so i'll make sure to keep this in mind for the future. I can't fix it with 2.x since it doesn't have an installer.

**Comment by Scr34mik** [comment]
Much obliged. It works now.
