### ISSUE TITLE
[HLMV] Animation playback speed adjustment

### ISSUE THREAD

**Issue by SPRKH** [Solokiller/HL_Tools#42]
The animation playback speed slider ranges from 0-200. The slider itself is always set to 30 fps by default (looks like at least), even if the actual animations are compiled to be played back at a different speed.

After adjusting the playback speed with the slider it is impossible to set it back to the normal speed. There is no indicator showing at what rate the animation is playing, nor is there a snap or button to reset it to the default speed. Displaying a multiplier (1x speed, 2x, 0.5x, etc.) instead of a range (0-200 fps?) might be a more suitable alternative.

For now the only way to get it back to the normal playback speed is to restart the program.

**Comment by SamVanheer** [comment]
I'll add an indicator showing the current FPS and provide a means to reset it. I'll allow for a way to change the slider to a multiplier instead of an FPS setting.

**Comment by Solokiller** [comment]
The slider values are now hidden, and a spin box control has been added to let you specify the speed as a framerate multiplier. Values in the range [0, 10] are allowed and can be specified as fractional values.

Pressing the up and down buttons or arrow keys changes by 0.1 seconds, page up and page down changes by 1 second.

The setting has always been a framerate multiplier just like the game's pev->framerate value, but the slider used the range [0, 200] because fractional values can't be represented by sliders. Since the value is now shown by the spin box as a fractional value this implementation detail is now hidden.
