### ISSUE TITLE
I cant't use many tabs now (Load Model, compile, recompile, help etc.)

### ISSUE THREAD

**Issue by Nathan2Nathan** [Solokiller/HL_Tools#55]
I think this triggered when I tried to use  edit QC file in the application, to access it when it said what would you like to open this file with I selected the model viewer after that when clicking on these tabs they do nothing and display an error called **error code 2** file dialogue failed
![badlife](https://user-images.githubusercontent.com/48526472/54296644-360d2280-45ad-11e9-8d11-50151b17cdda.JPG)

**Comment by SamVanheer** [comment]
I've looked into this, WxWidgets shows this error when the underlying window system fails. Error code 2 means the dialog failed to initialize, which usually happens when there isn't enough memory available.

Make sure your system has enough memory available to run the viewer. If this only happens when you perform a specific series of steps there may be a memory leak in the viewer somewhere. In that case, please describe the steps you took to get this error.

**Comment by Nathan2Nathan** [comment]
I waited a few days then it worked again but I couldn't compile my models,
I switched my studiomdl. And it works perfectly again
