### ISSUE TITLE
the model viewer uses too much the cpu.. 

### ISSUE THREAD

**Issue by sixcentgeorge** [Solokiller/HL_Tools#66]
your release has the same "bug" as previous versions i downloaded and used , that were made by Neil "Jed" Jedrzejewski (jed@wunderboy.org) http:///www.wunderboy.org .
right after you open it , it use a cpu or a core at full load all time.. i check with an old i7 that has nearly 10 years and 8 cores .. the software with no file loaded is using cpu at 12 or 13 % .. knowing that 100/8 = 12.5 ..
that was terrible at the time of pentium duo .. with two or four "cores" when one is at full load all time that makes the pc goes too hot quickly..  .. i am sure you ll get the bug and calm that cool software

**Comment by CS-PRO1** [comment]
Yea I have that too, 50% usage without a model being even loaded

**Comment by sixcentgeorge** [comment]
there must be a loop that has no end.. and that kills the model rendering either..sadly he has disappeared may be in the black hole websites of moddb or svencoop ..[:8

**Comment by Solokiller** [comment]
This happens because HLMV uses idle events to handle the frame rendering logic. It's unavoidable as a result. I can look into ways to reduce the frequency in cases like no model being loaded but i can't promise any improvements.

**Comment by sixcentgeorge** [comment]
good news you are back..
are you able to provide me a dll for a mod ? something close to opposing force but with few changes like few monsters from sweet half life  ..
i have made a giant Mix that has more than 200 Maps .. coming from several mods : pov, decay shl...  i want also it to play coop but not only like human , like aliens king pin or Tor ..

**Comment by sixcentgeorge** [comment]
sadly he has disappeared may be in the black hole websites of moddb or svencoop ..[:8
or some green beast like the Shrek or from Star Wars...

**Comment by Solokiller** [comment]
I've added an option to use a timer for frame logic instead of using idle events. This eliminates the CPU issues but has a much lower maximum framerate. On my system i can run at ~352 FPS with idle events and only ~65 FPS when using a timer.

Make sure to set the FPS limit to the highest setting to maximize the potential FPS.

Regarding your request for mod development, i don't get involved with specific mods' development and what you describe is Sven Co-op, so you should just use that.
