### ISSUE TITLE
Create installer to set up file associations, directory permissions, etc

### ISSUE THREAD

**Issue by Solokiller** [Solokiller/HL_Tools#91]
Create an installer to install HLAM 1.

- [x] Create installer
- [x] Set up file associations

**Comment by JoelTroch** [comment]
If [NSIS](https://nsis.sourceforge.io/Main_Page) is chosen as installer, [OpenRCT2's NSIS script](https://github.com/OpenRCT2/OpenRCT2/tree/develop/distribution/windows) would be a good reference and/or starting point since they have stuff related to OS architecture, uninstaller, desktop/start menu shortcuts, UAC detection/elevation, install/update check, get Windows version, check if program instance is running and some other things. Stuff that HLMV 3 could use.

**Comment by Solokiller** [comment]
Qt has its own installer framework: https://doc.qt.io/qtinstallerframework/index.html

I'll consider NSIS if Qt's framework doesn't work out.

**Comment by Solokiller** [comment]
I've set up the necessary configuration for the installer. It will install the program and provide a checkbox to associate the `.mdl` file extension with the program. However if there is already an association for it (e.g. Jed's model viewer) then it won't change that.

The batch file `CreateInstaller.bat` in `installer` will create the file `HalfLifeAssetManagerInstaller.exe` in the same directory. Qt Must be installed in the default directory for this to work. If you need to use the batch file with a non-standard path or if the path inside that installation has changed (e.g. new version) then you should modify the path.
